# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rofi-allthemes = {
    pname = "rofi-allthemes";
    version = "9d27f13bc7aabeaf755a32fcc640713256f7433e";
    src = fetchgit {
      url = "https://github.com/adi1090x/rofi";
      rev = "9d27f13bc7aabeaf755a32fcc640713256f7433e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-wwLcb7z5jCKgKPY5mNhYIoPvKbVO3PwULrJ+Lm3Ra7g=";
    };
    date = "2025-02-28";
  };
}
