# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rofi-allthemes = {
    pname = "rofi-allthemes";
    version = "b3be0c4d24d2967b6828d6ea01d993aa3ab04470";
    src = fetchgit {
      url = "https://github.com/Stormfox2/rofi-allthemes";
      rev = "b3be0c4d24d2967b6828d6ea01d993aa3ab04470";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-nkqY10JJGv/NJN78JS73C4MvRz8toxIcq3deywVaA4M=";
    };
    date = "2025-02-28";
  };
}
